#!/usr/bin/python

import sys
from selenium import webdriver
from pyvirtualdisplay import Display
from selenium.webdriver.common.keys import Keys

display = Display(visible = 0, size = (1024, 768))
display.start()

driver = webdriver.Firefox()
driver.get(str(sys.argv[1]))
print driver.title

driver.close()
display.stop()