#!/usr/bin/ruby

require_relative "PhishTank"
require_relative "VirtualMachine"

numOfSites = ARGV[0].to_i

tank = PhishTank.new
sites = tank.get_sites

vm = VirtualMachine.new
vm.start

numOfSites.times do |i|

	site = sites[i]

end

vm.stop